# Generated by Django 2.2.28 on 2023-06-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_hello'),
    ]

    operations = [
        migrations.AddField(
            model_name='hello',
            name='lkkkd',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
