# Generated by Django 2.2.28 on 2023-06-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hello_lkkkd'),
    ]

    operations = [
        migrations.AddField(
            model_name='hello',
            name='ksdjjd',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
