# Generated by Django 2.2.28 on 2023-06-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_hello_ksdjjd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hello',
            name='lkkkd',
        ),
        migrations.AddField(
            model_name='hello',
            name='lkkkdffssd',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='hello',
            name='ffqegfgsd',
            field=models.BigIntegerField(blank=True),
        ),
    ]
