# Generated by Django 2.2.28 on 2023-07-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_hi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hello',
            name='lkkkdffssdkj',
        ),
        migrations.AddField(
            model_name='hi',
            name='erewewwe',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
