# Generated by Django 2.2.28 on 2023-07-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20230720_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hii',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdafasfsaf', models.BigIntegerField()),
            ],
        ),
    ]
